import { test, expect } from '@playwright/test';
const routes=['/','/about','/academics','/admissions','/student-life','/gallery','/contact'];
for(const width of [1440,390]){
 test(`All pages render without errors or overflow at ${width}px`,async({page})=>{
  await page.setViewportSize({width,height:1000});const errors=[];page.on('pageerror',error=>errors.push(error.message));page.on('console',message=>{if(message.type()==='error')errors.push(message.text())});
  for(const route of routes){const response=await page.goto(route);expect(response.status()).toBe(200);await expect(page.locator('h1')).toHaveCount(1);await expect(page).toHaveTitle(/Eunivans/);await expect(page.locator('main')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);expect(await page.locator('img').evaluateAll(images=>images.every(image=>image.complete&&image.naturalWidth>0))).toBe(true);await page.screenshot({path:`test-results/${width}-${route.replaceAll('/','')||'home'}.png`,fullPage:true});}
  expect(errors).toEqual([]);
 });
}
test('Mobile navigation closes on selection and Escape',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto('/');const menu=page.getByRole('button',{name:'Open menu'});await menu.click();await expect(page.getByRole('navigation',{name:'Mobile navigation'})).toBeVisible();await page.keyboard.press('Escape');await expect(menu).toBeFocused();await menu.click();await page.getByRole('navigation',{name:'Mobile navigation'}).getByRole('link',{name:'Academics',exact:true}).click();await expect(page).toHaveURL(/academics/);await expect(page.getByRole('navigation',{name:'Mobile navigation'})).toHaveCount(0)});
test('Gallery filtering, keyboard navigation and focus restoration',async({page})=>{await page.goto('/gallery');await page.getByRole('button',{name:'Achievements',exact:true}).click();await expect(page.locator('.gallery-item')).toHaveCount(1);await page.getByRole('button',{name:'All',exact:true}).click();const trigger=page.getByRole('button',{name:'View Internal spelling competition',exact:true});await trigger.click();await expect(page.getByRole('dialog')).toBeVisible();await page.keyboard.press('ArrowRight');await expect(page.getByRole('dialog').getByRole('heading')).toHaveText('Graduation & prize-giving');await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);await expect(trigger).toBeFocused()});
for(const route of ['/admissions','/contact'])test(`${route} form validation and honest demo success`,async({page})=>{await page.goto(route);await page.getByRole('button',{name:'Preview enquiry submission'}).click();await expect(page.locator('.error').first()).toBeVisible();await page.getByLabel(route==='/admissions'?'Parent or guardian’s name':'Your name').fill('Test Guardian');await page.getByLabel('Telephone number',{exact:true}).fill('0244674934');await page.getByLabel('Email address',{exact:true}).fill('test@example.com');if(route==='/admissions'){await page.getByLabel('Child’s name',{exact:true}).fill('Test Child');await page.getByLabel('Programme or class of interest').selectOption('Kindergarten');await page.getByLabel('Child’s current age').fill('5');await page.getByLabel('Preferred contact method').selectOption('Email')}await page.getByLabel('Message',{exact:true}).fill('Synthetic local form test.');await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Preview enquiry submission'}).click();await expect(page.getByRole('button',{name:'Checking enquiry…'})).toBeDisabled();await expect(page.getByRole('status')).toContainText('nothing was sent');await expect(page.locator('.error')).toHaveCount(0)});
test('Contact links, SEO endpoints, internal routes and 404',async({page,request})=>{await page.goto('/contact');await expect(page.locator('a[href="tel:+233244674934"]').first()).toBeVisible();await expect(page.locator('a[href="tel:+233244376748"]').first()).toBeVisible();await expect(page.locator('a[href="mailto:eunivanseduk2@gmail.com"]').first()).toBeVisible();await expect(page.locator('a[href="https://wa.me/233244674934"]').first()).toBeVisible();const paths=new Set();for(const route of routes){await page.goto(route);for(const href of await page.locator('a[href^="/"]').evaluateAll(links=>links.map(a=>a.getAttribute('href'))))paths.add(href);const structured=JSON.parse(await page.locator('script[type="application/ld+json"]').textContent());expect(structured['@type']).toBe('EducationalOrganization')}for(const path of paths){const response=await request.get(path.split('#')[0]);expect(response.status()).toBe(200);if(path.includes('#')){await page.goto(path);await expect(page.locator(`#${path.split('#')[1]}`)).toHaveCount(1)}}for(const route of ['/robots.txt','/sitemap.xml','/opengraph-image','/icon.svg'])expect((await request.get(route)).status()).toBe(200);expect((await page.goto('/missing-page')).status()).toBe(404);await expect(page.getByRole('link',{name:'Back to home'})).toBeVisible()});
