import Link from 'next/link';
import Image from 'next/image';
import * as Icons from 'lucide-react';
import { programmes, values, school } from '../lib/content';
const icons = {Sprout: Icons.Sprout, BookOpen: Icons.BookOpen, GraduationCap: Icons.GraduationCap};
export function Brand(){return <Link className="brand" href="/" aria-label="Eunivans Educational Centre home"><span className="brand-mark"><Image className="brand-logo" src="/images/logo.jpeg" alt="" width={48} height={48} style={{width:'100%',height:'100%',objectFit:'contain',borderRadius:'50%'}}/></span><span>EUNIVANS<small>EDUCATIONAL CENTRE</small></span></Link>}
export function SectionHeading({eyebrow,title,children,light=false}){return <div className={`section-heading ${light?'light':''}`}><span className="eyebrow"><i/>{eyebrow}</span><h2>{title}</h2>{children&&<p>{children}</p>}</div>}
export function PageHero({eyebrow,title,children}){return <section className="page-hero"><div className="container"><div className="breadcrumb"><Link href="/">Home</Link><span>/</span>{eyebrow}</div><span className="eyebrow gold">{eyebrow}</span><h1>{title}</h1><p>{children}</p></div><div className="hero-orbit" aria-hidden="true"/></section>}
export function ProgrammeCard({programme,index}){const Icon=icons[programme.icon];return <article className="programme-card"><div className="card-top"><span className="icon-box"><Icon size={28}/></span><span className="card-number">0{index+1}</span></div><span className="mini-label">{programme.ages}</span><h3>{programme.title}</h3><p>{programme.description}</p><ul>{programme.areas.map(a=><li key={a}><Icons.Check size={15}/>{a}</li>)}</ul><Link className="text-link" href={`/academics#${programme.slug}`}>Explore programme <Icons.ArrowUpRight size={18}/></Link></article>}
export function Programmes(){return <section className="section tint"><div className="container"><div className="heading-row"><SectionHeading eyebrow="A foundation for every stage" title="Small beginnings. Bright futures.">From their very first words to their next big step, we grow with your child.</SectionHeading><Link className="text-link" href="/academics">Our academics <Icons.ArrowUpRight size={18}/></Link></div><div className="grid three">{programmes.map((p,i)=><ProgrammeCard key={p.slug} programme={p} index={i}/>)}</div></div></section>}
export function Values(){const IconSet=[Icons.ShieldCheck,Icons.Star,Icons.Trophy,Icons.BookOpen,Icons.Users];return <div className="values-grid">{values.map((v,i)=>{const Icon=IconSet[i];return <article className={`value-card ${i<2?'emphasis':''}`} key={v}><Icon size={27}/><h3>{v}</h3><p>{['Doing what is right, every day.','Giving our best in all we do.','Growing through consistent effort.','Learning with purpose and respect.','Achieving more, together.'][i]}</p></article>})}</div>}
export function StatisticsSection(){return <section className="stats"><div className="container stats-grid">{[['2006','The year our story began'],['20','Years of holistic education'],['3','Academic departments'],['5','Values that guide us']].map(([n,t])=><div key={t}><strong>{n}<span>✦</span></strong><p>{t}</p></div>)}</div></section>}
export function CallToAction(){return <section className="cta-section"><div className="container cta"><div><span className="eyebrow gold">Their future starts here</span><h2>Give your child a strong foundation in knowledge, character and confidence.</h2><p>Let’s talk about the next chapter in your child’s education.</p></div><div className="cta-buttons"><Link className="button gold-button" href="/admissions">Enquire About Admission <Icons.ArrowUpRight size={18}/></Link><a className="button outline-light" href={`tel:${school.phoneHref}`}><Icons.Phone size={17}/> Call the School</a></div></div></section>}
export function AchievementCard({item}){return <article className="achievement-card"><Link href="/gallery" className="image-wrap"><Image src={item.src} alt={item.alt} width={1200} height={850} sizes="(max-width: 700px) 100vw, 33vw" loading="eager"/><span className="image-tag">Photo pending</span></Link><div><span className="mini-label">{item.category}</span><h3><Link href="/gallery">{item.title}</Link></h3><p>School photograph and verified event details will be added here.</p><Link className="text-link" href="/gallery">View gallery <Icons.ArrowRight size={16}/></Link></div></article>}
export function Philosophy(){return <div className="grid three philosophy">{[[Icons.BookOpen,'The head','Knowledge that opens doors.'],[Icons.Heart,'The heart','Character that guides choices.'],[Icons.Sprout,'The hands','Skills that turn learning into action.']].map(([Icon,title,text])=><article key={title}><Icon/><h3>{title}</h3><p>{text}</p></article>)}</div>}
